channels:
- conda-forge
dependencies:
- python=3.11.3
- pip<=23.1.2
- pip:
  - mlflow==2.22.0
  - cloudpickle==3.1.1
  - numpy==2.2.1
  - pandas==2.2.3
  - torch==2.7.0
  - tqdm==4.67.1
name: mlflow-env
